component_depth: 2
languages:
- name: cpp
  production:
    exclude:
      - /src/.*\.Tests/.*\.h
      - /src/.*\.Tests/.*\.cpp
  test:
    include:
      - /src/.*\.Tests/.*\.h
      - /src/.*\.Tests/.*\.cpp
